### ISSUE TITLE
[Bug] Incorrect player suggestion for /msg on Velocity

### ISSUE THREAD

**Issue by Mrredstone5230** [fabianmakila/ProxyChat#63]
Running velocity, it's possible for the plugin to think that some players are online, even though they are not. For example, if you make a player join the server, but cancel the request on the joining world phase, that player's name will show up in the tab-complete of user arguments, even though the player isn't connected to the server.

From my understanding, it's caused by this line.
https://github.com/fabianmakila/ProxyChat/blob/cb40bd0e2b6ed619b784b00b40ad3fdded008908/velocity/src/main/java/fi/fabianadrian/proxychat/velocity/listener/LoginDisconnectListener.java#L24

**Comment by fabianmakila** [comment]
This should now be fixed in the latest release.

**Comment by Mrredstone5230** [comment]
Thanks a lot!
